export type StorefrontProductModel = {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  badge?: string;
  imageUrl: string;
  categoryId: string;
  rating: number;
  origin: string;
  grindType: string;
  roastLevel: string;
  tastingNotes: string[];
  brewMethods: string[];
  intensity: number;
  stockLabel: string;
  commercialBadges: string[];
  freeShippingEligible: boolean;
};
